# Generated by Django 3.0.6 on 2020-05-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('emp_id', models.IntegerField()),
                ('upload_file', models.FileField(upload_to='documents')),
            ],
            options={
                'verbose_name_plural': 'Employee Details',
            },
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
