# Generated by Django 3.0.6 on 2020-05-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20200526_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
